### ISSUE TITLE
Error from confluence

### ISSUE THREAD

**Issue by fr-ivasic** [andygolubev/integration-cookbook#3]
Hello, 

this looks nice and easy to use.   
However, I moved that on the gitlab, it looks that authentication is accepting only a confluence password not really a token?   
On curl the authentication looks something like:  
`curl -H "Authorization: Bearer <token>" `  
(no need for username with token usage)?

However, trying that on gitlab for now with password, after authentication getting the error 
```
npx @markdown-confluence/cli publish \ --confluenceBaseUrl "$CONFLUENCE_BASE_URL" \ --confluenceParentId "$CONFLUENCE_PARENT_ID" \ --atlassianUserName "$ATLASSIAN_USERNAME" \ --atlassianApiToken "$ATLASSIAN_API_TOKEN" \ --contentRoot "docs" \ --folderToPublish "."
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│   Error:                                                                     │
│   <!DOCTYPE html>                                                            │
│   <html>                                                                     │
│   <head>                                                                     │
│   <title>Page Not Found - sonnen</title>                                     │
```

The parent page exists, that's sure, and user has privilege to edit the page, I tested that as well.  
Also, seems that proper path (at least on gitlab pipeline ) is `contentRoot "docs"` not `contentRoot "/docs"`  (the last one is showing that directory doesn't exist).     
Tested with  `contentRoot "docs/"` the same result. 

Also, I tried to remove `--folderToPublish "."` the same result.

I don't know what is missing here?

I tested the docker locally, but I couldn't really authenticate. Maybe to put that in a separate issue.
Thanks.

**Comment by spdr870** [comment]
I use a variant on this script, but it does work with a token. Just put your email in 'login' and then your API key in 'password'.

BTW, I also use gitlab.

This is my gitlab.yml
```
variables:
  GIT_DEPTH: 50
  LOGIN: [EMAIL-REDACTED]
  PASSWORD: [API-KEY-REDACTED]
    
stages:
  - build

build:
  stage: build
  image: "python:3.10"
  tags:
    - docker
  script:
    - python -m pip install --upgrade pip
    - pip install -r ./publisher/requirements.txt
    - python3 ./publisher/main.py --login="$LOGIN" --password="$PASSWORD"
```
